version: "2"

# browse http://localhost:8080/ 
# follow the installation dialogue


services:

  db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  
  # db:
  #   image: postgres:10
  #   restart: always
  #   ports:
  #     - 8081:5432
  #   environment:
  #     POSTGRES_PASSWORD: example

  web:
    image: wordpress
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - db:mysql  # mysql = database name in the wp container
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant